OTH: Update docker file - added user

diff --git a/image-sabre-assist/S2iScripts/assemble b/image-sabre-assist/S2iScripts/assemble
--- a/image-sabre-assist/S2iScripts/assemble
+++ b/image-sabre-assist/S2iScripts/assemble
@@ -1,14 +1,19 @@
 #!/bin/bash -e
 
-if [ ! -z ${S2I_DEBUG} ]; then
-	echo "turning on assembly debug";
-  set -x
-fi
+echo "Assemble started ";
+
+
+#if [ ! -z ${S2I_DEBUG} ]; then
+#	echo "turning on assembly debug";
+#  set -x
+#fi
+
+
 
 # Binary deployment is a single war
-if [ $(ls /opt/app/src/*.jar | wc -l) -eq 1 ]; then
-  mv /opt/app/src/*.jar /opt/app/openshift-app.jar
-else
-  echo "Jar not found in /opt/app/src/"
-  exit 1
-fi
+#if [ $(ls /opt/app/src/*.jar | wc -l) -eq 1 ]; then
+#  mv /opt/app/src/*.jar /opt/app/openshift-app.jar
+#else
+#  echo "Jar not found in /opt/app/src/"
+#  exit 1
+#fi
